name: Project manage Restuarant
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    run-on: ubuntu-latest

    step:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-versions: 22.11
          cache: npm

      - name: Install dependencies
        run: npm install
      - name: Run unit test
        run: npm run test
